### ISSUE TITLE
Request html page?

### ISSUE THREAD

**Issue by Gargo** [3lvis/Networking#117]
I've checked readme file but it is still unclear for me - how to request just a page? for example, main page from "youtube.com"?

This library always tries to convert the data into json (and of course can't) and so it returns no data but error only. Yes, I tried advices from "Choosing a content type" but I still can't understand what I'm doing wrong

**Comment by 3lvis** [comment]
You just blew my mind. Why would you want to do that? I use this library mainly for REST interactions, that's why this use case wasn't included in the beginning. What is your use case? I think it could be added if the use case is common enough, for edge cases might be more useful for you to just use NSURLSession.

**Comment by Gargo** [comment]
I just wanted to try something different from NSURLSession. But thanks for advice.
There are a lot of cases in which automatical json parsing is harmful. For example, OneDrive may return error both as json and html page for the same request.
And yes, I understand that there is a special sdk for OneDrive but I have just suggested a case

**Comment by 3lvis** [comment]
Closing for now. Let's reconsider it in the future if there are similar requests.
