### ISSUE TITLE
Installing with Carthage with --platform iOS still installs all platform frameworks

### ISSUE THREAD

**Issue by rajohns08** [3lvis/Networking#127]

**Comment by 3lvis** [comment]
Do you have any ideas on how to fix that? I'm not sure how that works.

Also, would be nice to understand what's the problem with having it in all the platforms?

**Comment by rajohns08** [comment]
Not sure how to fix, but the benefit of only having the iOS platform is it is quicker to download/clone using carthage.

**Comment by 3lvis** [comment]
I'll have a look, thanks a lot!

**Comment by 3lvis** [comment]
Look like Alamofire's works because they don't take the time to add a pre-loaded archived version of the framework. [Here's one example](https://github.com/Alamofire/Alamofire/releases/tag/3.4.2). Meanwhile in Networking I add a precompiled zip file of the frameworks, in this way using `carthage update` should be much faster in Networking than in Alamofire. The downside is that Carthage doesn't know how to avoid getting all the platforms.

## Missing .zip file in Alamofire
![group1](https://cloud.githubusercontent.com/assets/1088217/18299635/ad118fc4-74c2-11e6-9140-5fe4548c431d.png)

## Framework .zip file in Networking
![group2](https://cloud.githubusercontent.com/assets/1088217/18299644/bebbef08-74c2-11e6-9b6a-aca96091cc85.png)

**Comment by rajohns08** [comment]
Not sure if this helps, but I noticed when pointing to your swift3 branch, it worked correctly (only the iOS platform was downloaded)

**Comment by 3lvis** [comment]
It's because in the Swift 3 branch, I'm not adding the .zip file.

**Comment by 3lvis** [comment]
<img width="907" alt="screen shot 2016-09-07 at 6 19 21 am" src="https://cloud.githubusercontent.com/assets/1088217/18299695/1a494dca-74c3-11e6-9e10-c2d8908f4ce9.png">

**Comment by 3lvis** [comment]
More info https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by 3lvis** [comment]
You can ear more about it from it's creator in this talk:

https://youtu.be/3BqR6_SsD8o?t=18m39s

<img width="1012" alt="screen shot 2016-09-07 at 6 25 43 am" src="https://cloud.githubusercontent.com/assets/1088217/18299778/ee626d3a-74c3-11e6-8a93-6a04a6b7a5a1.png">

**Comment by 3lvis** [comment]
For me using a library that has the prebuilt binaries works much faster than using another library that doesn't have them, even if that means sending all the platforms since it doesn't need to build anything, just downloads.

**Comment by 3lvis** [comment]
Closing now since I don't see a way how we could solve this without removing all the benefits of Prebuilt binaries. Let me know if you find something about it.
